language: bash
services: docker

install:
  - git clone https://github.com/ganjarsetia/docker-list-files-folder.git
  - cp .env.example .env

script:
  - docker-compose build
  - docker-compose up -d
  - curl http://localhost:3001/
  - docker-compose down
after_script:
  - docker images
